{
    "76de2da91adb26344e0484a127d2d2d36e2d01de": {
        "authored_data": "2014 Jun 17 20:26",
        "commit.message": "DELTASPIKE-638 - Fix Checkstyle/formatting/rat issues\n",
        "commit.author.name": "Rafael Benevides",
        "pcid": "91d09ca1d0978781d39620929a1ae64687b6388b",
        "changes": {
            "deltaspike/core/impl/src/main/java/org/apache/deltaspike/core/impl/exception/control/ExceptionHandlerBroadcaster.java": {
                "old": {
                    "(None, None)": [
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        29,
                        30,
                        31,
                        41,
                        42
                    ],
                    "('org.apache.deltaspike.core.impl.exception.control#ExceptionHandlerBroadcaster', None)": [
                        51,
                        52,
                        53,
                        54
                    ],
                    "('org.apache.deltaspike.core.impl.exception.control#ExceptionHandlerBroadcaster', 'executeHandlers(ExceptionToCatchEvent,BeanManager)')": [
                        57,
                        79,
                        80
                    ]
                },
                "new": {
                    "(None, None)": [
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        36,
                        37,
                        38,
                        39,
                        40,
                        42,
                        43
                    ],
                    "('org.apache.deltaspike.core.impl.exception.control#ExceptionHandlerBroadcaster', None)": [
                        52,
                        53,
                        54,
                        55,
                        56,
                        57,
                        58
                    ],
                    "('org.apache.deltaspike.core.impl.exception.control#ExceptionHandlerBroadcaster', 'executeHandlers(ExceptionToCatchEvent,BeanManager)')": [
                        61,
                        83,
                        84
                    ]
                }
            }
        }
    },
    "91d09ca1d0978781d39620929a1ae64687b6388b": {
        "authored_data": "2014 Jun 16 20:27",
        "commit.message": "Looks like I missed one case.\n\nThe tests now pass as expected.\n",
        "commit.author.name": "Jason Porter",
        "pcid": "9e665402c55f50f8389a02b8cfd68f053fc27398",
        "changes": {
            "deltaspike/core/impl/src/main/java/org/apache/deltaspike/core/impl/exception/control/ExceptionHandlerBroadcaster.java": {
                "old": {
                    "('org.apache.deltaspike.core.impl.exception.control#ExceptionHandlerBroadcaster', None)": [
                        53
                    ],
                    "('org.apache.deltaspike.core.impl.exception.control#ExceptionHandlerBroadcaster', 'executeHandlers(ExceptionToCatchEvent,BeanManager)')": [
                        60,
                        79,
                        122,
                        123,
                        125,
                        126
                    ]
                },
                "new": {
                    "('org.apache.deltaspike.core.impl.exception.control#ExceptionHandlerBroadcaster', None)": [
                        53
                    ],
                    "('org.apache.deltaspike.core.impl.exception.control#ExceptionHandlerBroadcaster', 'executeHandlers(ExceptionToCatchEvent,BeanManager)')": [
                        60,
                        79,
                        122,
                        124
                    ]
                }
            }
        }
    },
    "9e665402c55f50f8389a02b8cfd68f053fc27398": {
        "authored_data": "2014 Jun 16 20:01",
        "commit.message": "Should fix up DELTASPIKE-638\n\nOr at least make things a bit easier to follow.\n",
        "commit.author.name": "Jason Porter",
        "pcid": "21cf0a6b6f2de569bb80fc619c58d21a71b116df",
        "changes": {
            "deltaspike/core/impl/src/test/java/org/apache/deltaspike/test/core/impl/exception/control/flow/RethrowHandler.java": {
                "new": {
                    "('org.apache.deltaspike.test.core.impl.exception.control.flow#RethrowHandler', None)": [
                        30,
                        31,
                        32,
                        43,
                        47,
                        48
                    ],
                    "('org.apache.deltaspike.test.core.impl.exception.control.flow#RethrowHandler', 'handleInbound(ExceptionEvent)')": [
                        44,
                        45,
                        46
                    ],
                    "('org.apache.deltaspike.test.core.impl.exception.control.flow#RethrowHandler', 'isIaeHandlerCalled')": [
                        49,
                        50,
                        51
                    ],
                    "(None, None)": [
                        52
                    ]
                }
            },
            "deltaspike/core/impl/src/test/java/org/apache/deltaspike/test/core/impl/exception/control/flow/RethrowTest.java": {
                "old": {
                    "('org.apache.deltaspike.test.core.impl.exception.control.flow#RethrowTest', 'assertOutboundRethrow')": [
                        55
                    ],
                    "('org.apache.deltaspike.test.core.impl.exception.control.flow#RethrowTest', 'assertInboundRethrow')": [
                        61
                    ]
                },
                "new": {
                    "(None, None)": [
                        36,
                        37,
                        82
                    ],
                    "('org.apache.deltaspike.test.core.impl.exception.control.flow#RethrowTest', 'assertOutboundRethrow')": [
                        57,
                        58,
                        59,
                        60,
                        61,
                        62,
                        63,
                        64,
                        65
                    ],
                    "('org.apache.deltaspike.test.core.impl.exception.control.flow#RethrowTest', None)": [
                        66
                    ],
                    "('org.apache.deltaspike.test.core.impl.exception.control.flow#RethrowTest', 'assertInboundRethrow')": [
                        72,
                        73,
                        74,
                        75,
                        76,
                        77,
                        78,
                        79,
                        80,
                        81
                    ]
                }
            }
        }
    }
}